-- ============================================================================
-- Naprawa kolumny id w tabeli declarations
-- ============================================================================
-- Problem: Kolumna id jest zdefiniowana jako GENERATED ALWAYS AS IDENTITY
-- co uniemożliwia INSERT nawet z wartością DEFAULT/NULL
--
-- Rozwiązanie: Zmienić na GENERATED BY DEFAULT AS IDENTITY
-- ============================================================================

-- Sprawdź aktualną definicję:
-- SELECT column_name, column_default, is_identity, identity_generation
-- FROM information_schema.columns
-- WHERE table_name = 'declarations' AND column_name = 'id';

-- Usuń istniejącą kolumnę identity
ALTER TABLE public.declarations
ALTER COLUMN id DROP IDENTITY IF EXISTS;

-- Dodaj ponownie jako GENERATED BY DEFAULT (zamiast GENERATED ALWAYS)
ALTER TABLE public.declarations
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Weryfikacja:
-- SELECT column_name, column_default, is_identity, identity_generation
-- FROM information_schema.columns
-- WHERE table_name = 'declarations' AND column_name = 'id';
--
-- Powinno pokazać: identity_generation = 'BY DEFAULT'
